### PR TITLE
fix 2d_array_err

### PR DESCRIPTION
**Pull request by M-iceberg**

### CODE REVIEW

**Comment by M-iceberg** [comment]
./AzurePipelines run

**Comment by darobs** [comment]
>                 T* new_row = malloc_2(two_d_array->cols, sizeof(T));                                                                                                                         \

This only affects test code.

---
In reply to: [1996051274](https://github.com/Azure/c-util/pull/371#issuecomment-1996051274) [](http://example.com/codeflow?ancestors=1996051274)

---
Refers to: inc/c_util/two_d_array_ll.h:205 in 9f34761. [](commit_id = 9f347618f7af0bfbd4d8e3ccdf550fd0cc6ed11a, deletion_comment = False)

**Review by darobs — APPROVED** [review]
Considering the comment is only a problem if `sizeof(C)` != `sizeof(T)`, this change can move forward.

**Pull request merged**
